name: ASCII WORKFLOW

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List files
          run: ls -lrta
        
        - name: Running the script
          run: |
            chmod +x ascii-generate.sh
            ./ascii-generate.sh
        

