name: ASCII WORKFLOW

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: Print ASCII Characters
          run: cowsay -f dragon "Run Run Dragon...is here" >> dragon.txt
        
        - name: Check dragon file
          run: grep -i "dragon" dragon.txt
        
        - name: Read file
          run: cat dragon.txt

        - name: list files
          run: ls -ltra
