name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: List and Read files
          run: |
            echo "Welcome to GitHub Actions"
            ls -ltra
            cat README.md

        - name: Print ASCII Characters
          run: cowsay -f dragon "I'm the runner for Dragon..." >> dragon.txt
